import type { ReactNode } from 'react';
import './globals.css';
import NavBar from '../components/NavBar';
import CalculatorProvider from '../components/providers/CalculatorProvider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CalculatorProvider>
          <NavBar />
          <main className="mx-auto max-w-5xl px-4 py-6">{children}</main>
        </CalculatorProvider>
      </body>
    </html>
  );
}
