name: update staging
on: [workflow_dispatch]
jobs:
  build:
    name: Copy files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build tailwind css
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
      - run: npm run tailwind:build
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USERNAME }}
        key: ${{ secrets.STAGING_KEY }}
        port: ${{ secrets.STAGING_PORT }}
        source: "*"
        target: ${{ secrets.STAGING_PATH }}

